---
baseurl: "https://ostrichzero.com"
languageCode: "en-us"
title: "OstrichZero"
params:
    GoogleAnalyticsId: "UA-26604080-3"
    FullName: "OstrichZero"
    AvatarImage: ""
    BannerImage: "graphics/website_banner.png"
    Github: ""
    Twitter: ""
    Stackoverflow: ""
    Linkedin: ""
    title: It's Monday
    date: "Mar 1, 2015"
    SiteTitle: "OstrichZero"
    image_name: //static.ostrichzero.com/images/comics/20150301_mondayowl.png
    previous_image: //static.ostrichzero.com/images/comics/20150115_bears.png
    previous_post_path: comics/20150115_bears
---
