---
baseurl: "https://ostrichzero.com"
languageCode: "en-us"
title: "OstrichZero"
params:
    GoogleAnalyticsId: "UA-26604080-3"
    FullName: "OstrichZero"
    AvatarImage: ""
    BannerImage: "/graphics/website_banner.png"
    Github: ""
    Twitter: ""
    Stackoverflow: ""
    Linkedin: ""
    SiteTitle: "OstrichZero"
---
